name: "depth_unet_ts"
backend: "pytorch_libtorch"
max_batch_size: 8

input [
  { name: "INPUT__0" data_type: TYPE_FP32 dims: [ 3, 224, 224 ] }
]

output [
  { name: "OUTPUT__0" data_type: TYPE_FP32 dims: [ 1, 224, 224 ] }
]

instance_group [
  { kind: KIND_CPU, count: 1 }   // <-- CPU instance
]

dynamic_batching {
  preferred_batch_size: [ 4, 8 ]
  max_queue_delay_microseconds: 20000
}
